version: "3"

services:
    mysql:
        image: mysql:8.0.16
        container_name: servatrice_mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root-password
            - MYSQL_DATABASE=servatrice
            - MYSQL_USER=servatrice
            - MYSQL_PASSWORD=password
        volumes:
            - $PWD/mysql/schema/servatrice.sql:/docker-entrypoint-initdb.d/servatrice.sql
            - ./mysql/mount:/var/lib/mysql
        restart: unless-stopped
        logging:
            options:
                max-size: 10m

    servatrice:
        image: saadbruno/servatrice:2.7.6
        container_name: servatrice_server
        depends_on:
            - mysql
        ports:
            - "4747:4747"
            - "4748:4748"
        entrypoint: "/bin/bash -c 'sleep 10; servatrice --config /tmp/Servatrice/servatrice.ini --log-to-console'"
        volumes:
            - ./Servatrice:/tmp/Servatrice
        restart: unless-stopped
        logging:
            options:
                max-size: 10m
